### ISSUE TITLE
Other tags inside pre tag

### ISSUE THREAD

**Issue by maltiez2** [cenkalti/pyhtml#17]
When inserting other tags inside pre tag all tag final formating is kept resulting in extra spaces and new lines inside pre content.
Python code:
```
html(
	div(div(div(
		pre(class_="wiki")(
			["Some text",br,a(href="link")("link"),br,"some text"]
		)
	)))
)
```

Html code:
```
<!DOCTYPE html>
<html>
  <div>
    <div>
      <div>
        <pre class="wiki">Some text<br/>          <a href="link">
            link
          </a><br/>some text</pre>
      </div>
    </div>
  </div>
</html>
```

Result:
```
Some text
          
            link
          
some text
```

**Comment by cenkalti** [comment]
@maltiez2 sorry for the late reply, I must have missed this issue notification.

`pre` tag is usually used for marking the text that is already pre-formatted. So may I ask why are using PyHTML tags inside `pre`? What's your use case?

Can you also write what should be the expected output please?
