### ISSUE TITLE
Create modules for django template language

### ISSUE THREAD

**Issue by mishavetl** [cenkalti/pyhtml#7]
I suggest to create modules for django template language.

Sorry for my bad english. It is not my native language.

**Comment by arpit1997** [comment]
@mishavetl 
When we are on the topic of modules i suggest that you convert your project to a standard format which uses following:
- make a new src folder and put all your main source files there. 
- put all travis ci files, readme, license in the root of your repo
- follow a single code style like pep8 or something.
other than that it is a good project. 
ping me if you find any mistakes. 
:smile:
