### ISSUE TITLE
Support for screen reader attributes (`aria-*`)

### ISSUE THREAD

**Issue by nihlaeth** [cenkalti/pyhtml#8]
according to [w3c bootstrap documentation](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp):

> To help improve accessibility for people using screen readers, you should include the aria-label="close"   attribute, when creating a close button.

Currently it is not possible to set the `aria-*` attributes at in class initialisation, because `aria_*` arguments are not translated like `data_*` arguments are.

I'd be happy to provide a pull request if you wish.

**Comment by cenkalti** [comment]
Uploaded new version to PyPI: https://pypi.python.org/pypi/PyHTML
